// utils
export const UTILS_THEME_CHANGE = "UTILS_THEME_CHANGE";
export const UTILS_DOWNLOAD_SONG_STARTED = "UTILS_DOWNLOAD_SONG_STARTED";
export const UTILS_DOWNLOAD_SONG_FINISHED = "UTILS_DOWNLOAD_SONG_FINISHED";
export const UTILS_OPEN_CONTENT = "UTILS_OPEN_CONTENT";

// Alert
export const ALERT_SET = "ALERT_SET";
export const ALERT_REMOVE = "ALERT_REMOVE"; 

// Authentication
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_CONFIRM = "AUTH_CONFIRM";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_SIGNUP_CLEAR = "AUTH_SIGNUP_CLEAR";

// Admin
export const ADMIN_SONG_DELETE = "ADMIN_SONG_DELETE";
export const ADMIN_SONG_UPDATE = "ADMIN_SONG_UPDATE";

// User
export const USER = "USER";
export const USER_ERRORS = "USER_ERRORS";

// Room 
export const ROOM = "ROOM";
export const ROOM_CLEAR = "ROOM_CLEAR";
export const ROOM_CREATED_BY_ME = "ROOM_CREATED_BY_ME";
export const ROOM_SEARCH_ROOM = "ROOM_SEARCH_ROOM";
export const ROOM_SEARCH_SONG = "ROOM_SEARCH_SONG";
export const ROOM_CREATE = "ROOM_CREATE";
export const ROOM_DELETE = "ROOM_DELETE";
export const ROOM_PRIVATE_UPDATE = "ROOM_PRIVATE_UPDATE";
export const ROOM_ERROR = "ROOM_ERROR";
export const ROOM_CLEAR_ERROR = "ROOM_CLEAR_ERROR";

// Preview Playlist
export const PREVIEW_PLAYLIST = "PREVIEW_PLAYLIST";
export const PREVIEW_TOTAL_SONGS = "PREVIEW_TOTAL_SONGS";

// Upload Songs
export const UPLOAD_SONG_ERROR = "UPLOAD_SONG_ERROR";
export const UPLOAD_SONG_UPLOADING = "UPLOAD_SONG_UPLOADING";
export const UPLOAD_SONG_COMPLETED = "UPLOAD_SONG_COMPLETED";

// Playing Playlist
export const PLAYING_PREVIEW_SELECT_PLAYLIST = "PLAYING_PREVIEW_SELECT_PLAYLIST";
export const PLAYING_SELECT_PLAYLIST = "PLAYING_SELECT_PLAYLIST";
export const PLAYING_CHANGE_SONG = "PLAYING_CHANGE_SONG";
export const PLAYING_CLEAR = "PLAYING_CLEAR";

// Saved Playlist
export const SAVED_PLAYLIST = "SAVED_PLAYLIST";
export const SAVED_PLAYLIST_SAVE = "SAVED_PLAYLIST_SAVE"
export const SAVED_PLAYLIST_REMOVE = "SAVED_PLAYLIST_REMOVE";

// Customise Playlist
export const CUSTOMISE_PLAYLIST = "CUSTOMISE_PLAYLIST";
export const CUSTOMISE_PLAYLIST_CREATE = "CUSTOMISE_PLAYLIST_CREATE";
export const CUSTOMISE_PLAYLIST_DELETE = "CUSTOMISE_PLAYLIST_DELETE";
export const CUSTOMISE_PLAYLIST_UPDATE = "CUSTOMISE_PLAYLIST_UPDATE";

// Others Playlist
export const OTHERS_PLAYLIST = "OTHERS_PLAYLIST";
export const OTHERS_PLAYLIST_SEARCH = "OTHERS_PLAYLIST_SEARCH";
export const OTHERS_PLAYLIST_SAVE = "OTHERS_PLAYLIST_SAVE";
export const OTHERS_PLAYLIST_DELETE = "OTHERS_PLAYLIST_DELETE";